### ISSUE TITLE
annotation report / segmentation error 

### ISSUE THREAD

**Issue by apastore** [lamortenera/epicseg#12] opened 2016-08-31 20:20 UTC
Hi I would like to use the annotation feature of epicseg.R, But I keep on getting this error. 
do you have any suggestion?

thanks ! 

epicseg.R report  --model /cbio/cslab/home/pastore/nobackup/install/bcbio-vm/data/project/CLL/epigenomic/work/HMM/cll_248/5statemodel.txt \
>                   --segments ${outdir}/5statesegmentation.bed \
> --annot genes:/cbio/cslab/home/pastore/nobackup/bcbio/genomes/Hsapiens/hg19/refGene_hg19_TSS.bed 
loading epicseg
processing annotation: 'genes'
Error in if (any(ovstart >= npos)) stop("something went wrong in rescaling the coordinates") : 
  missing value where TRUE/FALSE needed
Calls: <Anonymous> ... sapply -> lapply -> FUN -> reportAnnot -> avgStateProfile
Execution halted
-bash-4.1$ cd cll_248/
-bash-4.1$ ls
5statecolors.txt  5statelmeans.txt  5statemodel.txt  5statesegmentation.bed  5statetable.txt   counts_refined_regions.bed
5statelmeans.png  5statemeans.png   5statenbs.png    5statetable.png         5statetransP.png  counts.txt
-bash-4.1$ head 5statesegmentation.bed 
chr1	200	564400	3	0	.	200	564400	31,120,180
chr1	570400	713200	3	0	.	570400	713200	31,120,180
chr1	713200	713800	4	0	.	713200	713800	251,154,153
chr1	713800	714800	1	0	.	713800	714800	51,160,44
chr1	714800	724000	3	0	.	714800	724000	31,120,180
chr1	727200	752600	3	0	.	727200	752600	31,120,180
chr1	752600	753000	4	0	.	752600	753000	251,154,153
chr1	753000	755200	3	0	.	753000	755200	31,120,180
chr1	755200	755600	4	0	.	755200	755600	251,154,153
chr1	755600	756800	3	0	.	755600	756800	31,120,180
-bash-4.1$ head /cbio/cslab/home/pastore/nobackup/bcbio/genomes/Hsapiens/hg19/refGene_hg19_TSS.bed 
chr19	50432773	50432773	NM_012346	NUP62	-
chr13	45563613	45563613	NM_012345	NUFIP1	-
chr1	36081	36081	NR_026818	FAM138A	-
chr14	74353317	74353317	NM_001242928	ZNF410	+
chr15	88799962	88799962	NM_001243101	NTRK3	-
chr1	42384378	42384378	NM_024503	HIVEP3	-
chr11	129872518	129872518	NR_024233	LINC00167	+
chr14	94463615	94463615	NR_024182	LINC00521	+
chr10	74033676	74033676	NM_019058	DDIT4	+
chr22	38035683	38035683	NM_018957	SH3BP1	+

**Comment by lamortenera** [comment] 2016-09-01 08:30
Hi, I assume that your BED files are tab-separated according to the BED standard. If they are, could you send me your two BED files (5statesegmentation.bed and  refGene_hg19_TSS.bed) so that I can see what is going on?

**Comment by apastore** [comment] 2016-09-01 15:44
Thanks Alessandro, yes they are both valid bed files. I have paste the head of each in my previous comment.  

Let me know if thi is enough.

**Comment by apastore** [comment] 2016-09-01 20:35
I heve seen that using the gene.bed you provide I can get the annotation, but still I have no success with my bed.

suggestion. It would be nice to output also a txt / png table with the average Signal on the interval for each state. (like in ChromHMM)

Thanks!

**Comment by apastore** [comment] 2016-09-01 21:10
I have used the bed annotation from ChromHMM an d they go through smooth.... so maybe just think about adding a note in the manual from where u can download working annotations... 

and maybe add the summary table feature this would be neat!


Thanks! for this nice tool!
Alessandro

**Comment by lamortenera** [comment] 2016-09-02 08:42
Hi apastore. It would be bad if epicseg was able to handle only specific types of BED files. So the issue is still open until I have time to look at it (this weekend). What is the summary table feature?

**Comment by apastore** [comment] 2016-09-02 18:11
I was thinking something like in figure 2(b) form the 111 Encode 2015 Nature paper as a summary feature table 

![screen shot 2016-09-02 at 14 04 55](https://cloud.githubusercontent.com/assets/6528310/18213586/f490499e-7116-11e6-8cce-1868acb18be0.png)

**Comment by lamortenera** [comment] 2016-09-10 19:20
Hi apastore. 
I found the issue with the bed files. It was a corner case that I didn't test in the past, which is when the regions that you provide have 0 length. I adapted the code and tidied it up a bit. Thanks a lot for spotting that, I am sure that at least a couple of people had the same problem and just gave up.
You should now be able to just reinstall epicseg from github using devtools, and the bug should disappear.

As for the summary table, I believe that the average profile that you wanted to do is a much more explicit representation of the same information. It is also more flexible, because you just need a BED file to use it.

Let me know if we can close this issue.

Thanks again!

**Comment by apastore** [comment] 2016-09-12 13:18
Thanks!
for me is closed issue!
Best,
Alessandro

**Closed** 2016-09-12 14:11 UTC
